/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.furst.faultrep.dialogs;

import com.furst.faultrep.Datamodule;
import com.furst.faultrep.tables.CreateDatamoduleTableModel;
import java.awt.Component;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableCellEditor;

/**
 *
 * @author tfurst
 */
public class CreateDataModuleDialog extends javax.swing.JDialog {

    /**
     * Creates new form CreateDataModuleDialog
     */
    private Datamodule dm;
    
    public CreateDataModuleDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create data module");
        setResizable(false);

        jTable1.setCellEditor(new UpperCaseCellEditor());
        jTable1.setModel(new CreateDatamoduleTableModel());
        jTable1.setEditingColumn(1);
        jScrollPane1.setViewportView(jTable1);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, submitButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        CreateDatamoduleTableModel m  = (CreateDatamoduleTableModel)jTable1.getModel();
        /*
        
            {"Model Identification Code",""  },
            {"System Difference Code",""},
            {"System Code",""},
            {"Sub-System Code",""},
            {"Sub-Sub-System Code",""},
            {"Assembly Code",""},
            {"Disassembly Code",""},
            {"Disassembly Code Variant",""},
            {"Information Code",""},
            {"Information Code Variant",""},
            {"Item Location Code",""},
            {"Technical Name",""},
            {"Information Name",""}
        
        */
        String modelic = m.getValueAt(0,1).toString().toUpperCase();
        String sysDiff = m.getValueAt(1,1).toString().toUpperCase();
        String sys = m.getValueAt(2,1).toString().toUpperCase();
        String subsys = m.getValueAt(3,1).toString().toUpperCase();
        String subsubsys = m.getValueAt(4,1).toString().toUpperCase();
        String assy = m.getValueAt(5,1).toString().toUpperCase();
        String disassy = m.getValueAt(6,1).toString().toUpperCase();
        String disassyv = m.getValueAt(7,1).toString().toUpperCase();
        String infocode = m.getValueAt(8,1).toString().toUpperCase();
        String infocodev = m.getValueAt(9,1).toString().toUpperCase();
        String itemloc = m.getValueAt(10,1).toString().toUpperCase();
        String tname = m.getValueAt(11,1).toString();
        String iname = m.getValueAt(12,1).toString();
        //String mod, String sysd, String sys, String sub, String subsub, String assy, String dis, String disv, String inf, String infv, String item, String tn, String inm
        dm = new Datamodule(modelic,sysDiff,sys,subsys,subsubsys,assy,disassy,disassyv,infocode,infocodev,itemloc,tname,iname);
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dm
     */
    public Datamodule getDm() {
        return dm;
    }
    
    class UpperCaseCellEditor extends javax.swing.AbstractCellEditor implements TableCellEditor{
        
        JComponent comp = new javax.swing.JTextField();
        
        public UpperCaseCellEditor()
        {
            super();
        }
        
        public Component getTableCellEditorComponent(JTable jt, Object val, boolean isSelected, int row, int col)
        {
            if(col == 1)
            {
                ((JTextField)comp).setText(((String)val).toUpperCase());
            }
            return comp;
        }
        
        @Override
        public Object getCellEditorValue() {
            return ((JTextField)comp).getText().toUpperCase();
        }
        
    }
}
